services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  
  ecommerce_userservice:
    build:
      context: .
      dockerfile: ./eCommerce.UserService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_CONNECTION_STRING=Host=db;Port=5432;Database=eCommerce-UserService;Username=postgres;Password=postgres123
    depends_on:
      - db

  ecommerce_productservice:
    build:
      context: .
      dockerfile: ./eCommerce.ProductService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_CONNECTION_STRING=Host=db;Port=5432;Database=eCommerce-ProductService;Username=postgres;Password=postgres123
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - db
      - rabbitmq

  ecommerce_gateway:
    build:
      context: .
      dockerfile: ./eCommerce.Gateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "3000:3000"
    depends_on:
      - ecommerce_userservice
  


volumes:
  postgres_data:
