services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  ecommerce_userservice:
    build:
      context: .
      dockerfile: ./eCommerce.UserService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_CONNECTION_STRING=Host=db;Port=5432;Database=eCommerce-UserService;Username=postgres;Password=postgres123
    depends_on:
      - db

  ecommerce_gateway:
    build:
      context: .
      dockerfile: ./eCommerce.Gateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "3000:3000"
    depends_on:
      - ecommerce_userservice
  


volumes:
  postgres_data:
